name: taxi
description: "Une application Flutter de taxi pour gérer les conducteurs et les passagers."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_code_scanner: ^1.0.1
  image_picker: ^1.1.2
  file_picker: ^8.3.1
  flutter_local_notifications: ^18.0.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1 
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.5
  mapbox_maps_flutter: ^2.5.1
  geolocator: ^13.0.2
  url_launcher: ^6.1.11
  device_info_plus: ^11.2.2
  share_plus: ^10.1.4
  http: ^1.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/default_profile.png
    - assets/icons/danger.png
    - assets/icons/notification.png
    - assets/icons/edit.png
    - assets/icons/qr.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  